name: Backend Continuous Integration

on:
  pull_request:
    branches: [ "main" ]
  
env:
  PYTHON_VERSION: 3.12.1
  IMAGE_REPO_NAME: backend
  IMAGE_TAG: latest
jobs:
  lint-job:
    name: LINT SUB JOB
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      
      - name: Install Linting Tools and Pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv flake8
  
      - name: Install dependencies
        run: |
          pipenv install

      - name: Run Linter
        run: |
          pipenv run lint
  test-job: 
    name: TEST SUB JOB
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
      
      - name: Install Dependencies For Testing
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pytest
  
      - name: Install dependencies
        run: |
          pipenv install
  
      - name: Run Backend Tests
        run: | 
          pipenv run test
  build-job:
    name: BUILD SUB JOB
    needs: [lint-job, test-job]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./starter/backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Docker Build
        run: |
          docker build -t ${{env.IMAGE_REPO_NAME}}:${{env.IMAGE_TAG}} .